### ISSUE TITLE
Relative window positioning support

### ISSUE THREAD

**Issue by TheWhiteWolves** [Krappa322/arcdps_healing_stats#16]
Using the totals and targets windows isn't that user friendly, currently the background is so large that you can'y place it anywhere without it being ove rthe top of something and theres no way to resize it, unlike in the base arc windows.

Another things that could to with looking at is that there is no relative positioning ability, e.g. I have all my windows setup to position based off a central window so they are all in the correct place.

**Comment by Krappa322** [comment]
You can resize any of the windows, there is a little thing in the bottom right corner that you drag to resize it

Relative positioning is definitely something to look into. I don't use that myself so if it's just based on my interest it's probably not going to happen for some time, but hey

**Comment by Krappa322** [comment]
Fixed in 2.3rc1 (https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v2.3rc1) :)
