### ISSUE TITLE
Relative window position doesn't handle negative X/Y values

### ISSUE THREAD

**Issue by TheWhiteWolves** [Krappa322/arcdps_healing_stats#20]
First just want to say thanks for adding the relative window positioning in 😄, now onto the bug

When entering a negative value for the X/Y value the positioning gets pushed to the side/top of the window instead of moving the number if pixels requested in the opposite direction, I've confirmed that base arc does this so its not that its not allowed on that side.

![image](https://user-images.githubusercontent.com/1471503/148826088-ced3c998-f10b-4909-9a00-ca8fd6cf3b7c.png)

**Comment by Krappa322** [comment]
That's an oopsie on my part, thanks for the report! :)

Fixed in 0b32c45d0e5e92548423dab06e7775c8f9145a7f

**Comment by Krappa322** [comment]
Released 2.4rc1 https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v2.4rc1 which should have this fixed
