### ISSUE TITLE
Name Truncate Under Display Options

### ISSUE THREAD

**Issue by aaronmott** [Krappa322/arcdps_healing_stats#21]
Normal arc windows have the ability to truncate player names. Display -> max name length.

Would be a great feature to compress the window and place it in a smaller space, thanks!

**Comment by Krappa322** [comment]
Thanks for the suggestion, will try to add that next release :)

**Comment by Krappa322** [comment]
Took a long time until the next release actually happened, but done now in 146ff72b3f192d3cf5dcf0518c46f64b767b6ea1, released in 2.5rc1 https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v2.5rc1
