### ISSUE TITLE
Keybind for heal stats windows

### ISSUE THREAD

**Issue by TheWhiteWolves** [Krappa322/arcdps_healing_stats#22]
Now I'm not sure if I've just missed this somewhere as I've not been able to find it but I would be nice to be able to set keybinds for opening/closing the window

**Comment by Krappa322** [comment]
Hi :)

You can configure keybind through right clicking on the healing stats window you want to set the keybind for

![image](https://user-images.githubusercontent.com/2184532/155586400-50362a12-1ad0-4461-8d75-0f667b71d9da.png)

**Comment by TheWhiteWolves** [comment]
Ahh cool, it is just me being blind then 😆
