### ISSUE TITLE
Game gets halted for access violation when using this addon in combination with Gw2Launcher

### ISSUE THREAD

**Issue by UmBottesWillen** [Krappa322/arcdps_healing_stats#27]
I've detailed the issue in full on the [issue tracker of Gw2Launcher](https://github.com/Healix/Gw2Launcher/issues/165#issuecomment-1210740215), but to sum it up, after setting up Gw2Launcher, my game got suspended for a memory access violation when moving windows or changing settings in ArcDPS. Through process of elimination it seems like this addon is responsible for the access violation, as the issue no longer occurred when it was not installed.

My setup is as follows:
- Win10 x64 21H2
- GW2 installed under "F:/Guild Wars 2"
- Gw2Launcher set up for multi-account use
- Relevant Gw2Launcher settings:
- - Guild Wars 2>Process priority>Above normal
- - Guild Wars 2>Processor affinity>Use all available processors
- - Guild Wars 2> Prioritize the in-game browser>Boost[...]
- - Guild Wars 2>Management>Mode>Virtual (though basic did not fix the issue either)
- - Guild Wars 2>Management>Localized execution>Enable localized execution
- - Guild Wars 2>Management>Desired level>Full
- - Guild Wars 2>Management>Synchronizing>Core
- ArcDPS installed in the folder created by Gw2Launcher
- [Killproof plugin](https://github.com/knoxfighter/arcdps-killproof.me-plugin), [Unofficial Extras plugin](https://github.com/Krappa322/arcdps_unofficial_extras_releases), [Boon Table plugin](https://github.com/knoxfighter/GW2-ArcDPS-Boon-Table) (renamed to `d3d11_arcdps_table.dll`) installed in addition to the healing stats plugin. All were up-to-date.

Edit: following is the ArcDPS read of all installed plugins. 
![arcdps log](https://user-images.githubusercontent.com/63181877/183994331-4f107d72-87d1-4f2d-81a5-e85dbc58af0a.jpg)

Edit 2: Using a Just-in-Time debugger confirms that the exception was triggered by the healing stats addon (translated):
`Thread 0x170 has ended with code 0 (0x0).
Exception error at 0x00007FF9178ABF3D (arcdps_healing_stats.dll) in Gw2-64.exe: Severe program termination requested`

**Comment by Krappa322** [comment]
Hi!

Thanks for reporting

Can you provide me with the arcdps crash log (addons/arcdps/arcdps_lastcrash.log)? Sadly I cannot do anything with the address referenced without knowing the base address for the healing stats addon when it crashed (which is written in the log).

Alternatively, you could get the base address of the module from the debugger

**Comment by Krappa322** [comment]
If you let me know what debugger you are using I can help you further on how to collect exactly what I'm looking for

**Comment by UmBottesWillen** [comment]
Hi, there is no crash log, since Windows killed the process as soon as it tried to call an invalid address. I've been using Visual Studio 2019 Community edition for the JIT debugging.

**Comment by Krappa322** [comment]
I think the easiest is probably if you download the pdb:
[kappa322.com/arcdps_healing_stats/2.5rc1/arcdps_healing_stats.pdb](kappa322.com/arcdps_healing_stats/2.5rc1/arcdps_healing_stats.pdb)

Put that next to the arcdps healing stats dll then take a screenshot of what you see in the "Call Stack" window in Visual Studio

**Comment by Krappa322** [comment]
![image](https://user-images.githubusercontent.com/2184532/184037467-c24dea60-8fdc-4d98-9696-b8d58ee16430.png)
Something like this

**Comment by UmBottesWillen** [comment]
Here's the call stack I got. I'll be off for today, if my help is still needed after this, I'll be back tomorrow.
![call_stack](https://user-images.githubusercontent.com/63181877/184039175-f0d53185-9b5e-4852-8b0f-26ac75966e0a.jpg)

**Comment by UmBottesWillen** [comment]
Since I figured the call stack won't be of too much use, I've created memory dumps of the processes in the hopes they'll be more useful.
[gw2_dumps_pw.zip.001.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305152/gw2_dumps_pw.zip.001.zip)
[gw2_dumps_pw.zip.002.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305154/gw2_dumps_pw.zip.002.zip)
[gw2_dumps_pw.zip.003.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305155/gw2_dumps_pw.zip.003.zip)
[gw2_dumps_pw.zip.004.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305156/gw2_dumps_pw.zip.004.zip)
[gw2_dumps_pw.zip.005.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305157/gw2_dumps_pw.zip.005.zip)
[gw2_dumps_pw.zip.006.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305159/gw2_dumps_pw.zip.006.zip)
[gw2_dumps_pw.zip.007.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305160/gw2_dumps_pw.zip.007.zip)
[gw2_dumps_pw.zip.008.zip](https://github.com/Krappa322/arcdps_healing_stats/files/9305153/gw2_dumps_pw.zip.008.zip)

Thanks to githubs wonderful file size limitation, I had to zip them, split them and then add the trailing `.zip`, so you'll have to remove the last for characters from each file name. The PW is your github name.

**Comment by Krappa322** [comment]
Hi, thank you for being helpful :)

However memory dumps are really not something you want to put on the internet. I've edited your comment and removed the links. The memory in question might contain things such as your gw2 password

**Comment by Krappa322** [comment]
I can however see that you are actually running multiple instances of healing stats - you have 2.5rc1 installed in bin64 and 2.6rc1 installed in the gw2 root folder

I'll try doing that myself and see if I can reproduce the crash :)

**Comment by Krappa322** [comment]
You have similar duplicate instances of all your addons - you might want to have a look at that ;)

**Comment by Krappa322** [comment]
Yup that does it, I can reproduce the crash. That should be all I need from you, thank you very much for the report and the help (it's really nice working with someone who knows how to use a debugger!). In the meanwhile you should be able to mitigate the crash by only running one instance of the addon

Arcdps prevents loading the same addon multiple times which is likely why you haven't seen more issues. This looks like it's some bug on my part when being loaded multiple times

**Comment by Krappa322** [comment]
This was determined to be caused by a bug in arcdps
