### ISSUE TITLE
Failed connection

### ISSUE THREAD

**Issue by NeXX451** [Krappa322/arcdps_healing_stats#28]
When I enable the live stat sharing I get an error telling me the connection failed. Looking at the logs I get this

Oct 20 22:39:20.464097 15892 I Log|SetLevel|Changed level to 1
Oct 20 22:39:21.535748 15892 I Client|SetEnabledStatus|Changed enabled status to false
Oct 20 22:39:21.537999 15488 D Client|Serve|Client was disabled, cancelling calls
Oct 20 22:39:21.538005 15488 D Client|Serve|Notified on tag 000002643D2352B0
Oct 20 22:39:21.538008 15488 D Client|Serve|(tag 000002643D2352B0) Got not-ok
Oct 20 22:39:21.538013 15488 D Client|Serve|(tag 000002643D2352B0) Connection to remote failed. Queued 0000026476361430 to get error code
Oct 20 22:39:21.538016 15488 D Client|Serve|(tag 000002643D2352B0) Was write, setting mWritePending to false
Oct 20 22:39:21.538017 15488 D Client|Serve|Notified on tag 00000264758E2500
Oct 20 22:39:21.538018 15488 D Client|Serve|(tag 00000264758E2500) Got not-ok
Oct 20 22:39:21.538018 15488 D Client|Serve|(tag 00000264758E2500) Remote broke connection
Oct 20 22:39:21.538020 15488 D Client|Serve|Notified on tag 0000026476361430
Oct 20 22:39:21.538021 15488 D Client|Serve|(tag 0000026476361430) got result 1 'CANCELLED' '' 0
Oct 20 22:39:26.415937 15892 I Client|SetEnabledStatus|Changed enabled status to true
Oct 20 22:39:26.419828 15488 D Client|Serve|Opening new connection to evtc-rpc.kappa322.com:443 connect_tag=000002643E8DA910, read_tag=000002643D4863E0, root_certs_size=264440

Somehow, it's not connecting to the RPC server at all, or I don't get the ssl certs.

**Comment by Krappa322** [comment]
Are there any logs after that? The ones here indicate success actually, you had it disabled at 22:39:21 then enabled it at 22:39:26 at which point it opened a connection. The error logs between those timestamps are the errors from the calls being cancelled when you disabled live stats sharing

**Comment by NeXX451** [comment]
Ok somethings going with my DNS server.. I just switched it to the google DNS and it works just fine. Thus it's a problem on my side.

**Comment by Krappa322** [comment]
👍
