### ISSUE TITLE
Healing stats not connecting to the server or connected and not displaying others

### ISSUE THREAD

**Issue by TesterKanok** [Krappa322/arcdps_healing_stats#37]
This started last night on the 23rd. People seem to not be able to stay connected to the server or if they are, no one else is showing up for them. Using the latest version from 2023 along with the latest version of arcdps 03/24/2024.
![image](https://github.com/Krappa322/arcdps_healing_stats/assets/142521088/4d852022-603d-43de-b174-52c22fd7d7ac)

**Comment by theextendedname** [comment]
Yes, I am seeing the same issue. Relaunching GW2 gets the connection to the RPC server going again. However, it failed again as soon as I entered WvW and joined a group. I will attempt to enable debug mode tonight for logs and may even do a packet cap.

**Comment by Krappa322** [comment]
Hi folks, thanks for the report. I have a fix for this, will post it momentarily. It is an issue op the client side and as such requires an update of the addon itself.

**Comment by Krappa322** [comment]
https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v2.9rc1

**Comment by theextendedname** [comment]
Thank you, Krappa322. The patch seems to work great.
