### ISSUE TITLE
[Feature Request] Live bars

### ISSUE THREAD

**Issue by MoXAriApph** [Krappa322/arcdps_healing_stats#4]
Would be nice to see live bars kinda like in Boon Table or area stats specifics, showing what makes up most of your healing at a glance.
By extension you could include "Effectiveness" as a bar, showing how effectively you're healing based on miss/hits.

Wasn't sure if this would be included with 
> Display a graph showing healing done over time (allowing visualisation of when healing pressure is high)

**Comment by Krappa322** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/2184532/111549954-7051c180-877d-11eb-8f8b-30ac8e3530af.png)

If so then that's available in 1.1rc1 :) https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v1.1rc1

**Comment by MoXAriApph** [comment]
> Is this what you mean?
> ![image](https://user-images.githubusercontent.com/2184532/111549954-7051c180-877d-11eb-8f8b-30ac8e3530af.png)
> 
> If so then that's available in 1.1rc1 :) https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v1.1rc1

Exactly that, github doesn't show prebuilds without going to releases
![SNAG-7433](https://user-images.githubusercontent.com/20781130/111581081-9fb8fc00-8786-11eb-9b40-b86f00965f03.png)

**Comment by Krappa322** [comment]
Yeah, I wish that it could show both latest release and latest pre-release but hey

**Comment by Krappa322** [comment]
Fixed by 03a3459985eab4bed6bf66a03bffe1a6923c9a13
